app/disques/urls.py
"""Routage."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from search.views import home, product, search, shelf

urlpatterns = (
    [
        path("", home, name="home"),
        path(
            "recherche",
            search,
            name="search",
        ),
        path(
            "bac/<str:slug>",
            shelf,
            name="shelf",
        ),
        path(
            "produit/<str:slug>",
            product,
            name="product",
        ),
        path("admin/", admin.site.urls),
        path(
            "sw.js",
            TemplateView.as_view(
                template_name="sw.js", content_type="application/javascript"
            ),
            name="sw.js",
        ),
        path(
            "manifest.json",
            TemplateView.as_view(
                template_name="manifest.json", content_type="application/json"
            ),
            name="manifest.json",
        ),
        path(
            "offline.html",
            TemplateView.as_view(
                template_name="offline.html",
            ),
            name="offline.html",
        ),
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

app/search/models.py
"""Modèles Search."""

import os
import traceback
import uuid
from datetime import timedelta
from functools import partial
from typing import TYPE_CHECKING

from core.helpers import notify
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models, transaction
from django.db.models import QuerySet
from django.db.models.manager import BaseManager
from django.forms.models import model_to_dict
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.module_loading import import_string
from django.utils.text import slugify
from django.utils.translation import gettext as _
from django_q.tasks import async_task
from djmoney.contrib.exchange.models import convert_money
from djmoney.models.fields import MoneyField

if TYPE_CHECKING:
    from .diggers import CrateDigger


def unique_slugify(instance: models.Model, string: str) -> str:
    """Assurance qu'un slug soit unique.

    Args:
        instance: une instance de modèle.
        string: la chaîne à slugifier.

    Returns:
        Un slug unique pour `instance`.
    """
    Model = instance.__class__
    unique_slug = slug = slugify(string)[:50]  # limite SlugField à 50 chars par défaut
    while Model.objects.filter(slug=unique_slug).exists():
        if len(slug) > 45:
            slug = slug[:45]
        unique_slug = f"{slug}-{get_random_string(length=4)}"
    return unique_slug


def digger_choices() -> list[tuple[str, str]]:
    """Liste les diggers disponibles."""
    diggers = []
    with os.scandir(settings.DIGGERS_PATH) as entries:
        for entry in entries:
            if not entry.name.startswith("__") and entry.name.endswith(".py"):
                digger, _ = os.path.splitext(entry.name)
                diggers.append((digger, digger))
    return diggers


def dig_it(dig_id: str) -> None:
    """Lancement d'une recherche sur un disquaire (aka un dig).

    Args:
        dig_id: id du dig à démarrer
    """
    dig = Dig.objects.get(pk=dig_id)
    dig.start()
    try:
        for product in dig.digger.dig():
            dig.keep(product)
    except Exception as exception:
        dig.failed(exception)
    else:
        dig.stop()


class Shop(models.Model):
    """Un disquaire."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(_("nom"), max_length=150)
    slug = models.SlugField(_("slug"))
    url = models.URLField(_("URL"))
    digger_name = models.CharField(_("digger"), choices=digger_choices(), max_length=50)
    logo = models.URLField(_("Logo"), blank=True)
    icon = models.URLField(_("Icône"), blank=True)
    created_at = models.DateTimeField(_("création"), auto_now_add=True)
    updated_at = models.DateTimeField(_("mise à jour"), auto_now=True)
    is_active = models.BooleanField(
        _("actif"),
        help_text=_("Un disquaire désactivé n’est plus testé/utilisé"),
        default=True,
    )
    description = models.TextField(
        _("informations complémentaires"),
        blank=True,
    )
    region = models.CharField(
        _("région"),
        choices=settings.REGION_CHOICES,
        max_length=2,
        blank=True,
    )
    is_independent = models.BooleanField(_("indépendant"), default=True)
    is_bm = models.BooleanField(_("physique"), default=False)
    is_marketplace = models.BooleanField(_("place de marché"), default=False)
    is_direct = models.BooleanField(
        _("direct"), help_text=_("Appartient au label / artiste"), default=False
    )

    class Meta:
        verbose_name = _("disquaire")
        verbose_name_plural = _("disquaires")
        ordering = ["name"]

    @property
    def digger_class(self) -> "CrateDigger":
        """Crate Digger utilisé pour le disquaire."""
        return import_string(f"search.diggers.{self.digger_name}.Digger")

    def __str__(self) -> str:
        """Retourne le nom du magasin."""
        return self.name

    def save(self, *args, **kwargs) -> None:
        """Génération du slug."""
        if not self.slug:
            self.slug = slugify(str(self))
        super().save(*args, **kwargs)

    def health_check(self) -> None:
        """Vérification de l'état de santé du magasin.

        Si trop de digs annulés dans un temps imparti on désactive le disquaire.
        """
        if not self.is_active:
            return

        if (
            Dig.objects.filter(
                shop=self,
                ended_at__gt=timezone.now() - settings.DIGS_MAX_FAILURE_WINDOW,
                status=settings.STATUS_CANCELLED,
            ).count()
            > settings.DIGS_MAX_FAILURE
        ):
            self.is_active = False
            self.save()
            message = "Dépassement du seuil d'erreur pour {self} 🙀"
            transaction.on_commit(partial(notify, message=message))


class Product(models.Model):
    """Un produit dans un magasin."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    slug = models.SlugField(_("slug"))
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE, related_name=_("products"))
    seller = models.CharField(_("vendeur"), max_length=100, blank=True)
    title = models.TextField(_("titre"), blank=False, null=False)
    image_url = models.URLField(
        _("URL de l’image"),
        blank=True,
    )
    medium = models.CharField(
        _("format"),
        choices=settings.MEDIA_CHOICES,
        max_length=10,
        default=settings.MEDIA_UNK,
    )
    url = models.URLField(_("URL"), blank=True, unique=True)
    created_at = models.DateTimeField(_("création"), auto_now_add=True)
    updated_at = models.DateTimeField(_("mise à jour"), auto_now=True)
    description = models.TextField(
        _("informations complémentaires"),
        blank=True,
    )
    price = MoneyField(
        _("prix"), max_digits=5, decimal_places=2, default_currency="EUR"
    )
    price_in_eur = MoneyField(
        _("prix en euros"),
        max_digits=5,
        decimal_places=2,
        blank=True,
        null=True,
        default_currency="EUR",
    )
    availability = models.CharField(
        _("disponibilité"),
        max_length=10,
        choices=settings.AVAILABILITY_CHOICES,
        default=settings.AVAILABILITY_UNK,
    )
    condition = models.CharField(
        _("état"),
        max_length=10,
        choices=settings.CONDITION_CHOICES,
        default=settings.CONDITION_UNK,
    )

    class Meta:
        verbose_name = _("produit")
        verbose_name_plural = _("produits")

    def __str__(self) -> str:
        """Retourne le titre, le format, le prix et le disquaire."""
        return f"{self.title} ({self.medium}) - {self.price} @ {self.shop}"

    def save(self, *args, **kwargs) -> None:
        """Mise à jour du prix en euros et slug."""
        if self.price:
            self.price_in_eur = convert_money(self.price, "EUR")
        if not self.slug:
            self.slug = unique_slugify(self, f"{self.shop.name} {self.title}")
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Page produit."""
        return reverse("product", args=[self.slug])

    @property
    def related_products(self) -> "QuerySet":
        """Produits liés (présents dans d'autres résultats de recherche)."""
        results_qs = Result.objects.filter(product=self).values("search")
        return (
            Product.objects.filter(sources__search__in=results_qs)
            .prefetch_related("shop")
            .distinct()
        )


class Search(models.Model):
    """Les recherches lancées sur le site."""

    QUERY_MIN_LENGTH = 3
    SEARCH_MAX_TTL = 24

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    query = models.TextField(
        _("recherche"), validators=[MinLengthValidator(QUERY_MIN_LENGTH)]
    )
    medium = models.CharField(
        _("format"),
        choices=settings.MEDIA_CHOICES,
        default=settings.MEDIA_UNK,
        max_length=10,
        blank=False,
    )
    slug = models.SlugField(_("slug"))
    created_at = models.DateTimeField(_("création"), auto_now_add=True)
    viewed_at = models.DateTimeField(_("dernière consultation"), blank=True, null=True)
    digged_at = models.DateTimeField(_("dernière exécution"), blank=True, null=True)

    class Meta:
        verbose_name = _("recherche")
        verbose_name_plural = _("recherches")
        constraints = [
            models.UniqueConstraint(
                fields=["query", "medium"], name="unique_query_medium"
            ),
        ]

    @property
    def title(self) -> str:
        """Raccourci vers __str__ en Title Case."""
        return str(self).title()

    @property
    def is_expired(self) -> bool:
        """True si la recherche a été lancé depuis plus de 24h."""
        if not self.digged_at or self.digged_at < timezone.now() - timedelta(
            hours=self.SEARCH_MAX_TTL
        ):
            return True
        return False

    @property
    def products(self) -> BaseManager["Product"]:
        """Raccourci vers les produits."""
        return Product.objects.filter(sources__search=self).all()

    @property
    def products_count(self) -> int:
        """Décompte des produits."""
        return Product.objects.filter(sources__search=self).count()

    @property
    def digging(self) -> bool:
        """A des digs en cours."""
        return self.digs.filter(
            status__in=[settings.STATUS_WAIT, settings.STATUS_RUNNING]
        ).exists()

    def __str__(self) -> str:
        """Retourne la requête + média (si précisé)."""
        if self.medium != settings.MEDIA_UNK:
            return f"{self.query} ({self.medium})"
        return self.query

    def save(self, *args, **kwargs):
        """Génération du slug et création des digs."""
        if not self.slug:
            self.slug = unique_slugify(self, str(self))

app/search/forms.py
"""Formulaires."""

from typing import TYPE_CHECKING

from django import forms
from django.conf import settings
from django.utils import timezone
from django.utils.translation import gettext as _

from .models import Search

if TYPE_CHECKING:
    from django.db.models import QuerySet


class SearchForm(forms.ModelForm):
    """Formulaire pour lancer une recherche."""

    class Meta:
        model = Search
        fields = ["query"]
        widgets = {"query": forms.TextInput}

    def validate_unique(self):
        """On ignore les validateurs d'unicité.

        On a une contrainte d'unicité sur `query` + `medium`, elle est prise en compte
        sur la méthode save en utilisant un `update_or_create`.
        """
        pass

    def save(self, commit=True) -> Search:
        """Les recherches sont uniques par `query` & medium, on `update_or_create`."""
        search, __ = Search.objects.update_or_create(
            query=self.cleaned_data["query"],
            defaults={"viewed_at": timezone.now()},
        )
        return search


class SearchFilterForm(forms.Form):
    """Formulaire de filtrage d'un bac."""

    MEDIUM_CHOICES = [("", _("Format"))] + settings.MEDIA_CHOICES
    AVAILABILITY_CHOICES = [("", _("Stock"))] + settings.AVAILABILITY_CHOICES
    CONDITION_CHOICES = [("", _("État"))] + settings.CONDITION_CHOICES

    query = forms.CharField(label=_("Filtre"), max_length=100, required=False)
    medium = forms.ChoiceField(
        label=_("Format"), choices=MEDIUM_CHOICES, required=False
    )
    availability = forms.ChoiceField(
        label=_("Stock"), choices=AVAILABILITY_CHOICES, required=False
    )
    condition = forms.ChoiceField(
        label=_("État"), choices=CONDITION_CHOICES, required=False
    )

    def filter_products(self, queryset: "QuerySet") -> "QuerySet":
        """Filtre la requête de récupération des produits.

        A utiliser après un `form.is_valid()` car on utilise `cleaned_data`

        Args:
            queryset: la requête produit

        Returns:
            La requête filtrée.
        """
        filters = self.cleaned_data
        if filters["query"]:
            queryset = queryset.filter(title__icontains=filters["query"])
        if filters["medium"]:
            queryset = queryset.filter(medium=filters["medium"])
        if filters["availability"]:
            queryset = queryset.filter(availability=filters["availability"])
        if filters["condition"]:
            queryset = queryset.filter(condition=filters["condition"])
        return queryset

app/search/views.py
"""Vues HTML pour la recherche."""

from http import HTTPStatus
from typing import TYPE_CHECKING

from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_GET, require_POST
from django.views.decorators.vary import vary_on_headers
from django_htmx.http import HTMX_STOP_POLLING, push_url, retarget

from .forms import SearchFilterForm, SearchForm
from .models import Product, Search

if TYPE_CHECKING:
    from django.http import HttpRequest, HttpResponse


@require_GET
def home(request: "HttpRequest") -> "HttpResponse":
    """Accueil."""
    context = {
        "products": Product.objects.order_by("?").all()[:35],
        "form": SearchForm(),
    }
    return render(request, "home.html", context)


@require_POST
@vary_on_headers("HX-Request")
def search(request: "HttpRequest") -> "HttpResponse":
    """Recherche."""
    form = SearchForm(request.POST)
    if form.is_valid():
        search = form.save()
        if not request.htmx:
            redirect(search)
        context = {
            "search": search,
            "products": search.products.prefetch_related("shop"),
            "filter_form": SearchFilterForm(),
        }
        response = render(request, "_shelf.html", context)
        return push_url(response, search.get_absolute_url())
    else:
        context = {"form": form}
        if not request.htmx:
            render(request, "search.html", context)
        response = render(request, "_search_form.html", context)
        return retarget(response, "#search")


@require_GET
@vary_on_headers("HX-Request")
def shelf(request: "HttpRequest", slug: str) -> "HttpResponse":
    """Bac à disques (résultats d'une recherche)."""
    search = get_object_or_404(Search, slug=slug)
    filter_form = SearchFilterForm(request.GET)

    products = search.products.prefetch_related("shop")

    if filter_form.is_valid():
        products = filter_form.filter_products(products)

    status: HTTPStatus | int = HTTPStatus.OK
    context = {
        "search": search,
        "products": products,
    }
    if request.htmx:
        if not search.digging:
            status = HTMX_STOP_POLLING
        template_name = "_products_table.html"
    else:
        context["form"] = SearchForm()
        context["filter_form"] = filter_form
        template_name = "shelf.html"
    return render(request, template_name, context, status=status)


@require_GET
@vary_on_headers("HX-Request")
def product(request: "HttpRequest", slug: str) -> "HttpResponse":
    """Page produit."""
    product = get_object_or_404(Product.objects.select_related("shop"), slug=slug)
    context = {"product": product}
    if request.htmx:
        template_name = "_product.html"
    else:
        context["form"] = SearchForm()
        template_name = "product.html"
    return render(request, template_name, context)

app/search/templates/_product.html
<article class="row mb-4">
  <div class="col-sm-4">
    {% thumbnail product.image_url "400x400" crop="80% top" as im %}
    <a href="{{ product.url }}" target="_blank">
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
        loading="lazy" class="img-thumbnail" alt="Pochette de {{ product.title }}">
    </a>
    {% endthumbnail %}
  </div>
  <div class="col-sm-8">
    <h1 class="h2"><a href="{{ product.url }}" target="_blank">{{ product.title }}</a>
    </h1>
    {% if product.description %}{{ product.description|linebreaks }}{% endif %}
    <p>
      <span
        class="badge text-bg-dark">{{ product.get_medium_display|default:'?' }}</span>
      <span class="badge text-bg-dark">{{ product.get_availability_display }}</span>
    </p>
    <p><a href="{{ product.url }}" target="_blank"
        class="btn btn-primary">{{ product.price_in_eur }} sur {{ product.shop }}</a>
    </p>
  </div>
</article>

<h2>Disques associés</h2>
<section class="row row-cols-2 row-cols-md-5 row-cols-lg-6 g-4">
  {% for product in product.related_products %}{% include "_product_card.html" %}{% endfor %}
</section>

app/search/templates/_product_card.html
<div class="col">
  <article class="card h-100" id="product_{{ product.pk }}">
    {% thumbnail product.image_url "300x300" crop="80% top" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
      loading="lazy" class="card-img-top" alt="Pochette de {{ product.title }}">
    {% endthumbnail %}
    <div class="card-body">
      <h5 class="card-title">
        <a href="{{ product.get_absolute_url }}" class="stretched-link"
          data-hx-boost="true" data-hx-target="main">{{ product.title }}</a>
      </h5>
      <p class="card-text">
        {% if product.medium %}
        <span class="medium">{{ product.get_medium_display }}</span>
        {% endif %}
        <span class="price">{{ product.price_in_eur }}</span>
        <span>{{ product.shop }}</span>
      </p>
    </div>
  </article>
</div>

app/search/templates/_product_tr.html
<tr data-hx-boost="true" data-hx-target="main">
  <td>
    {% thumbnail product.image_url "200x200" crop="80% top" as im %}
    <a href="{{ product.get_absolute_url }}">
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"
        loading="lazy" class="img-thumbnail" alt="Pochette de {{ product.title }}">
    </a>
    {% endthumbnail %}
  </td>
  <td>
    <h2 class="h6"><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
    </h2>
    {% if product.description %}{{ product.description|linebreaks }}{% endif %}
  </td>
  <td>{{ product.get_medium_display|default:'?' }}</td>
  <td>{{ product.price_in_eur }}</td>
  <td>{{ product.get_availability_display }}</td>
  <td><a href="{{ product.url }}" target="_blank">{{ product.shop }}</a></td>
</tr>

app/search/templates/_products_grid.html
<div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-4">
  {% for product in products %}{% include "_product_card.html" %}{% endfor %}
</div>

app/search/templates/_products_table.html
{% if not products %}
{% if search.digging %}
<p class="alert alert-info" role="alert">Recherche en cours...</p>
{% else %}
<p class="alert alert-warning" role="alert">Rien trouvé :-(</p>
{% endif %}
{% else %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Pochette</th>
      <th scope="col">Titre</th>
      <th scope="col">Média</th>
      <th scope="col">Prix</th>
      <th scope="col">Stock</th>
      <th scope="col">Disquaire</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    {% include "_product_tr.html" %}
    {% endfor %}
  </tbody>
</table>
{% endif %}

app/search/templates/_shelf.html
<h1 class="mb-4">Bac {{ search }}</h1>

<form class="row mb-4" data-hx-target="#results"
  data-hx-trigger="keyup delay:500ms, change"
  data-hx-get="{{ search.get_absolute_url }}" data-hx-push-url="true">
  <div class="col">
    {% render_field filter_form.query placeholder=filter_form.query.label type="search" class+="form-control" %}
  </div>
  <div class="col">
    {% render_field filter_form.medium class+="form-select" %}
  </div>
  <div class="col">
    {% render_field filter_form.availability class+="form-select" %}
  </div>
  <div class="col">
    {% render_field filter_form.condition class+="form-select" %}
  </div>
  <div class="col">
    <button class="btn btn-outline-success" type="submit" id="filter-btn">
      <span class="spinner-border spinner-border-sm htmx-indicator" role="status"
        aria-hidden="true">
        <span class="visually-hidden">En cours...</span>
      </span>
      Filter
    </button>
  </div>
</form>
<div id="results" class="table-responsive" data-hx-get="{{ search.get_absolute_url }}"
  data-hx-trigger="every 3s">
  {% include "_products_table.html" %}
</div>

app/search/templates/home.html
{% extends "base.html" %}

{% block content %}
{% include "_products_grid.html" with products=products only %}
{% endblock content %}

app/search/templates/product.html
{% extends "base.html" %}

{% block title %}{{ product }}{% endblock %}

{% block content %}
{% include "_product.html" %}
{% endblock content %}

app/search/templates/search.html
{% extends "base.html" %}

{% block title %}Bac {{ object }}{% endblock %}

{% block content %}
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger">
  <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger">
  <strong>{{ error|escape }}</strong>
</div>
{% endfor %}
{% endif %}
{% endblock content %}

app/search/templates/shelf.html
{% extends "base.html" %}

{% block title %}Bac {{ search }}{% endblock %}

{% block content %}
{% include "_shelf.html" %}
{% endblock content %}